#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#autostart
sxhkd &
picom --config $HOME/.config/picom.conf &
nitrogen --restore &
polybar &
feh --bg-scale $HOME/.config/sxhkd/wallpapers/wallpaper.jpg &
#end
